//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFTest.StudentOptionsService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StudentOptionsService.IStudentOptionsService")]
    public interface IStudentOptionsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentOptionsService/getActiveOptions", ReplyAction="http://tempuri.org/IStudentOptionsService/getActiveOptionsResponse")]
        string[] getActiveOptions();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentOptionsService/boolsubmitOptions", ReplyAction="http://tempuri.org/IStudentOptionsService/boolsubmitOptionsResponse")]
        bool boolsubmitOptions(string studentNumber, string firstName, string lastName, string firstOption, string secondOption, string thirdOption, string fourthOption);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStudentOptionsServiceChannel : WCFTest.StudentOptionsService.IStudentOptionsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StudentOptionsServiceClient : System.ServiceModel.ClientBase<WCFTest.StudentOptionsService.IStudentOptionsService>, WCFTest.StudentOptionsService.IStudentOptionsService {
        
        public StudentOptionsServiceClient() {
        }
        
        public StudentOptionsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StudentOptionsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StudentOptionsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StudentOptionsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] getActiveOptions() {
            return base.Channel.getActiveOptions();
        }
        
        public bool boolsubmitOptions(string studentNumber, string firstName, string lastName, string firstOption, string secondOption, string thirdOption, string fourthOption) {
            return base.Channel.boolsubmitOptions(studentNumber, firstName, lastName, firstOption, secondOption, thirdOption, fourthOption);
        }
    }
}
