//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("DiplomaOptionsModel", "FK_Choices_Options_First", "Options", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DiplomaOptionsModel.Option), "StudentOptionChoices", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DiplomaOptionsModel.StudentOptionChoice), true)]
[assembly: EdmRelationshipAttribute("DiplomaOptionsModel", "FK_Choices_Options_Fourth", "Options", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DiplomaOptionsModel.Option), "StudentOptionChoices", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DiplomaOptionsModel.StudentOptionChoice), true)]
[assembly: EdmRelationshipAttribute("DiplomaOptionsModel", "FK_Choices_Options_Second", "Options", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DiplomaOptionsModel.Option), "StudentOptionChoices", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DiplomaOptionsModel.StudentOptionChoice), true)]
[assembly: EdmRelationshipAttribute("DiplomaOptionsModel", "FK_Choices_Options_Third", "Options", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DiplomaOptionsModel.Option), "StudentOptionChoices", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DiplomaOptionsModel.StudentOptionChoice), true)]

#endregion

namespace DiplomaOptionsModel
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class DiplomaOptionsEntities1 : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new DiplomaOptionsEntities1 object using the connection string found in the 'DiplomaOptionsEntities1' section of the application configuration file.
        /// </summary>
        public DiplomaOptionsEntities1() : base("name=DiplomaOptionsEntities1", "DiplomaOptionsEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DiplomaOptionsEntities1 object.
        /// </summary>
        public DiplomaOptionsEntities1(string connectionString) : base(connectionString, "DiplomaOptionsEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DiplomaOptionsEntities1 object.
        /// </summary>
        public DiplomaOptionsEntities1(EntityConnection connection) : base(connection, "DiplomaOptionsEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Option> Options
        {
            get
            {
                if ((_Options == null))
                {
                    _Options = base.CreateObjectSet<Option>("Options");
                }
                return _Options;
            }
        }
        private ObjectSet<Option> _Options;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<StudentOptionChoice> StudentOptionChoices
        {
            get
            {
                if ((_StudentOptionChoices == null))
                {
                    _StudentOptionChoices = base.CreateObjectSet<StudentOptionChoice>("StudentOptionChoices");
                }
                return _StudentOptionChoices;
            }
        }
        private ObjectSet<StudentOptionChoice> _StudentOptionChoices;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Options EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToOptions(Option option)
        {
            base.AddObject("Options", option);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the StudentOptionChoices EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToStudentOptionChoices(StudentOptionChoice studentOptionChoice)
        {
            base.AddObject("StudentOptionChoices", studentOptionChoice);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DiplomaOptionsModel", Name="Option")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Option : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Option object.
        /// </summary>
        /// <param name="title">Initial value of the Title property.</param>
        /// <param name="isActive">Initial value of the IsActive property.</param>
        public static Option CreateOption(global::System.String title, global::System.Boolean isActive)
        {
            Option option = new Option();
            option.Title = title;
            option.IsActive = isActive;
            return option;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                if (_Title != value)
                {
                    OnTitleChanging(value);
                    ReportPropertyChanging("Title");
                    _Title = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Title");
                    OnTitleChanged();
                }
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsActive
        {
            get
            {
                return _IsActive;
            }
            set
            {
                OnIsActiveChanging(value);
                ReportPropertyChanging("IsActive");
                _IsActive = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsActive");
                OnIsActiveChanged();
            }
        }
        private global::System.Boolean _IsActive;
        partial void OnIsActiveChanging(global::System.Boolean value);
        partial void OnIsActiveChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DiplomaOptionsModel", "FK_Choices_Options_First", "StudentOptionChoices")]
        public EntityCollection<StudentOptionChoice> StudentOptionChoices
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<StudentOptionChoice>("DiplomaOptionsModel.FK_Choices_Options_First", "StudentOptionChoices");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<StudentOptionChoice>("DiplomaOptionsModel.FK_Choices_Options_First", "StudentOptionChoices", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DiplomaOptionsModel", "FK_Choices_Options_Fourth", "StudentOptionChoices")]
        public EntityCollection<StudentOptionChoice> StudentOptionChoices1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<StudentOptionChoice>("DiplomaOptionsModel.FK_Choices_Options_Fourth", "StudentOptionChoices");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<StudentOptionChoice>("DiplomaOptionsModel.FK_Choices_Options_Fourth", "StudentOptionChoices", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DiplomaOptionsModel", "FK_Choices_Options_Second", "StudentOptionChoices")]
        public EntityCollection<StudentOptionChoice> StudentOptionChoices2
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<StudentOptionChoice>("DiplomaOptionsModel.FK_Choices_Options_Second", "StudentOptionChoices");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<StudentOptionChoice>("DiplomaOptionsModel.FK_Choices_Options_Second", "StudentOptionChoices", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DiplomaOptionsModel", "FK_Choices_Options_Third", "StudentOptionChoices")]
        public EntityCollection<StudentOptionChoice> StudentOptionChoices3
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<StudentOptionChoice>("DiplomaOptionsModel.FK_Choices_Options_Third", "StudentOptionChoices");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<StudentOptionChoice>("DiplomaOptionsModel.FK_Choices_Options_Third", "StudentOptionChoices", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DiplomaOptionsModel", Name="StudentOptionChoice")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class StudentOptionChoice : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new StudentOptionChoice object.
        /// </summary>
        /// <param name="choiceId">Initial value of the ChoiceId property.</param>
        /// <param name="year">Initial value of the Year property.</param>
        /// <param name="studentNumber">Initial value of the StudentNumber property.</param>
        /// <param name="firstName">Initial value of the FirstName property.</param>
        /// <param name="lastName">Initial value of the LastName property.</param>
        /// <param name="firstChoice">Initial value of the FirstChoice property.</param>
        /// <param name="secondChoice">Initial value of the SecondChoice property.</param>
        /// <param name="thirdChoice">Initial value of the ThirdChoice property.</param>
        /// <param name="fourthChoice">Initial value of the FourthChoice property.</param>
        /// <param name="createDate">Initial value of the CreateDate property.</param>
        public static StudentOptionChoice CreateStudentOptionChoice(global::System.Int32 choiceId, global::System.Int32 year, global::System.String studentNumber, global::System.String firstName, global::System.String lastName, global::System.String firstChoice, global::System.String secondChoice, global::System.String thirdChoice, global::System.String fourthChoice, global::System.DateTime createDate)
        {
            StudentOptionChoice studentOptionChoice = new StudentOptionChoice();
            studentOptionChoice.ChoiceId = choiceId;
            studentOptionChoice.Year = year;
            studentOptionChoice.StudentNumber = studentNumber;
            studentOptionChoice.FirstName = firstName;
            studentOptionChoice.LastName = lastName;
            studentOptionChoice.FirstChoice = firstChoice;
            studentOptionChoice.SecondChoice = secondChoice;
            studentOptionChoice.ThirdChoice = thirdChoice;
            studentOptionChoice.FourthChoice = fourthChoice;
            studentOptionChoice.CreateDate = createDate;
            return studentOptionChoice;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ChoiceId
        {
            get
            {
                return _ChoiceId;
            }
            set
            {
                if (_ChoiceId != value)
                {
                    OnChoiceIdChanging(value);
                    ReportPropertyChanging("ChoiceId");
                    _ChoiceId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ChoiceId");
                    OnChoiceIdChanged();
                }
            }
        }
        private global::System.Int32 _ChoiceId;
        partial void OnChoiceIdChanging(global::System.Int32 value);
        partial void OnChoiceIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Year
        {
            get
            {
                return _Year;
            }
            set
            {
                OnYearChanging(value);
                ReportPropertyChanging("Year");
                _Year = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Year");
                OnYearChanged();
            }
        }
        private global::System.Int32 _Year;
        partial void OnYearChanging(global::System.Int32 value);
        partial void OnYearChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String StudentNumber
        {
            get
            {
                return _StudentNumber;
            }
            set
            {
                OnStudentNumberChanging(value);
                ReportPropertyChanging("StudentNumber");
                _StudentNumber = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("StudentNumber");
                OnStudentNumberChanged();
            }
        }
        private global::System.String _StudentNumber;
        partial void OnStudentNumberChanging(global::System.String value);
        partial void OnStudentNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FirstChoice
        {
            get
            {
                return _FirstChoice;
            }
            set
            {
                OnFirstChoiceChanging(value);
                ReportPropertyChanging("FirstChoice");
                _FirstChoice = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FirstChoice");
                OnFirstChoiceChanged();
            }
        }
        private global::System.String _FirstChoice;
        partial void OnFirstChoiceChanging(global::System.String value);
        partial void OnFirstChoiceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SecondChoice
        {
            get
            {
                return _SecondChoice;
            }
            set
            {
                OnSecondChoiceChanging(value);
                ReportPropertyChanging("SecondChoice");
                _SecondChoice = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SecondChoice");
                OnSecondChoiceChanged();
            }
        }
        private global::System.String _SecondChoice;
        partial void OnSecondChoiceChanging(global::System.String value);
        partial void OnSecondChoiceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ThirdChoice
        {
            get
            {
                return _ThirdChoice;
            }
            set
            {
                OnThirdChoiceChanging(value);
                ReportPropertyChanging("ThirdChoice");
                _ThirdChoice = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ThirdChoice");
                OnThirdChoiceChanged();
            }
        }
        private global::System.String _ThirdChoice;
        partial void OnThirdChoiceChanging(global::System.String value);
        partial void OnThirdChoiceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FourthChoice
        {
            get
            {
                return _FourthChoice;
            }
            set
            {
                OnFourthChoiceChanging(value);
                ReportPropertyChanging("FourthChoice");
                _FourthChoice = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FourthChoice");
                OnFourthChoiceChanged();
            }
        }
        private global::System.String _FourthChoice;
        partial void OnFourthChoiceChanging(global::System.String value);
        partial void OnFourthChoiceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreateDate
        {
            get
            {
                return _CreateDate;
            }
            set
            {
                OnCreateDateChanging(value);
                ReportPropertyChanging("CreateDate");
                _CreateDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateDate");
                OnCreateDateChanged();
            }
        }
        private global::System.DateTime _CreateDate;
        partial void OnCreateDateChanging(global::System.DateTime value);
        partial void OnCreateDateChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DiplomaOptionsModel", "FK_Choices_Options_First", "Options")]
        public Option Option
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Option>("DiplomaOptionsModel.FK_Choices_Options_First", "Options").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Option>("DiplomaOptionsModel.FK_Choices_Options_First", "Options").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Option> OptionReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Option>("DiplomaOptionsModel.FK_Choices_Options_First", "Options");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Option>("DiplomaOptionsModel.FK_Choices_Options_First", "Options", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DiplomaOptionsModel", "FK_Choices_Options_Fourth", "Options")]
        public Option Option1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Option>("DiplomaOptionsModel.FK_Choices_Options_Fourth", "Options").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Option>("DiplomaOptionsModel.FK_Choices_Options_Fourth", "Options").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Option> Option1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Option>("DiplomaOptionsModel.FK_Choices_Options_Fourth", "Options");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Option>("DiplomaOptionsModel.FK_Choices_Options_Fourth", "Options", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DiplomaOptionsModel", "FK_Choices_Options_Second", "Options")]
        public Option Option2
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Option>("DiplomaOptionsModel.FK_Choices_Options_Second", "Options").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Option>("DiplomaOptionsModel.FK_Choices_Options_Second", "Options").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Option> Option2Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Option>("DiplomaOptionsModel.FK_Choices_Options_Second", "Options");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Option>("DiplomaOptionsModel.FK_Choices_Options_Second", "Options", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DiplomaOptionsModel", "FK_Choices_Options_Third", "Options")]
        public Option Option3
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Option>("DiplomaOptionsModel.FK_Choices_Options_Third", "Options").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Option>("DiplomaOptionsModel.FK_Choices_Options_Third", "Options").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Option> Option3Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Option>("DiplomaOptionsModel.FK_Choices_Options_Third", "Options");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Option>("DiplomaOptionsModel.FK_Choices_Options_Third", "Options", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
